frontend/app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='index'),
    path('add/',views.add,name='add'),
    path('delete/',views.delete,name='delete'),
    path('cargar/',views.cargaMasiva,name='carga'),
]

frontend/frontend/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
]

frontend/app/models.py
from django.db import models

# Create your models here.

frontend/app/forms.py
from django import forms

class FileForm(forms.Form):
    file = forms.FileField(label='file')

class AddForm(forms.Form):
    name = forms.CharField(label="name")
    anime = forms.CharField(label="anime")
    desc = forms.CharField(label="desc")
    image = forms.CharField(label="image")

class DeleteForm(forms.Form):
    name = forms.CharField(label='Nombre')

frontend/app/views.py
from django.shortcuts import render
from app.forms import  FileForm,AddForm,DeleteForm
import requests
# Create your views here.

endpoint = 'http://127.0.0.1:4000/'
def home(request):
    context = {
        'characters':[]
    }
    try:

        response = requests.get(endpoint + 'showall')
        characters = response.json()
        context['characters'] = characters
    except:
        print('API no esta levantada')
    return render(request,'index.html',context)

def add(request):
    if request.method == 'POST':
        form = AddForm(request.POST)
        if form.is_valid():
            json_data = form.cleaned_data
            response = requests.post(endpoint + 'add',json = json_data)

            if response.ok:
                return  render(request,'add.html',{'form':form})
        return render(request, 'add.html', {'form': form})
    return render(request,'add.html')

def delete(request):
    if request.method == 'POST':
        form = DeleteForm(request.POST)
        if form.is_valid():
            json_data = form.cleaned_data
            response =  requests.delete(endpoint+'delete/'+json_data['name'])
    else:
        form = DeleteForm()
    return render(request,'delete.html',{'form':form})

def cargaMasiva(request):
    ctx = {
        'content':None,
        'response':None,
    }
    if request.method == 'POST':
        form = FileForm(request.POST,request.FILES)
        if form.is_valid():
            f = request.FILES['file']
            print(f.name)
            xml_binary = f.read()
            xml = xml_binary.decode('utf-8')
            ctx['content'] = xml
            reponse = requests.post(endpoint + 'addVarios',data=xml_binary)
            print(reponse)
            if reponse.ok:
                ctx['response'] = 'archivo cargado correcto'
            else:
                ctx['response'] = 'se encontro un error en el archivo'
        else:
            return render(request,'carga.html')
    return render(request,'carga.html',ctx)

frontend/app/templates/add.html
{% extends "base.html" %}
{% block content %}

<div class="container py-4">
    <h1 style="text-align: center;"> Inserta un nuevo personaje </h1>
  </div>
  <div class="container py-5">
  <div class="row">
      <div class="col">
        {% if form.errors %}
        <p style="color: red;"> Por favor, completa todos los campos, todos son necesarios </p>
        {% endif %}
          <form action="/add/" method="POST">
              {% csrf_token %}
              <div class="mb-3">
                  <label for="name" class="form-label">Name:</label>
                  <input type="text" class="form-control" id="id_name" name ="name">
              </div>
                <div class="mb-3">
                  <label for="anime" class="form-label">Anime:</label>
                  <input type="text" class="form-control" id="id_anime" name ="anime">
                  </div>
              <div class="mb-3">
                <label for="desc" class="form-label">Description:</label>
                <input type="text" class="form-control" id="id_desc" name ="desc">
                <div id="DescHelp" class="form-text">Please, insert at least 100 characters</div>.</div>
              </div>
              <div class="mb-3">
                <label for="image" class="form-label">Image link:</label>
                <input type="text" class="form-control" id="id_image" name="image">
              </div>
              <button type="submit" class="btn btn-dark btn-lg">Agregar Personaje</button>
            </form>
          </div>
      </div>
  </div>

{% endblock content %}

frontend/app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    {% if title %}
        <title>Anime Characters - {{title}}</title>
    {% else %}
        <title> Anime Characters </title>
    {% endif %}
</head>
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'index' %}">LIST</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'add' %}">Insertar</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'delete' %}">Eliminar</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'carga' %}">Cargar Archivo</a>
          </li>
          <!--{% if user %}
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">{{user}}</a>
          </li>
          {% endif %}
        -->
        </ul>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-secondary" type="submit">¨Buscar</button>
        </form>
      </div>
    </div>
  </nav>
  </header>

  <main role="main">
    {% block content %}{% endblock %}
  </main>

frontend/app/templates/carga.html
{% extends "base.html" %}
{% block content %}
    <div class="container py-2">
        <h1 style="text-align: center;"> Carga Masiva </h1>
    </div>
    <div class="container py-2">
        <form action="/cargar/" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="file">Cargar un archivo</label>
        <br>
        <input type="file" id="file" name="file" accept="text/xml">
        <div class="container py-3">
            {% if content %}
                <textarea label="textarea" name="textarea" rows="20" cols="70">{{content}}</textarea>
                <textarea label="textarea" name="textarea2" rows="20" cols="70">{{response}}</textarea>
            {% else %}
                <textarea style="margin-right: 1rem;" label="textarea" name="textarea" rows="20" cols="70"></textarea>
                <textarea label="textarea" name="textarea2" rows="20" cols="70"></textarea>
            {% endif %}
        </div>
        <button type="submit" class="btn btn-dark btn-lg">Enviar</button>
        </form>
    </div>
{% endblock content %}

frontend/app/templates/delete.html
{% extends "base.html" %}
{% block content %}
<div class="container py-4">
    <h1 style="text-align: center;"> Elimina un personaje </h1>
  </div>
<div class="container py-5">
    <div class="row">
        <div class="col">
            {% if form.errors %}
                <p style="color: red;"> Por favor, es necesario proveer un nombre de personaje </p>
            {% endif %}
            <form action="" method="POST"> {% csrf_token %}
                <table>
                {{ form.as_table }}
                </table>
                <input type="submit" class="btn btn-dark btn-lg" value="Eliminar Personaje">
            </form>
        </div>
    </div>
</div>
{% endblock content %}

frontend/app/templates/index.html
{% extends "base.html" %}
{% block content %}
<section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading">Characters List JL</h1>
      <p class="lead text-muted">Por favor no me juzguen, no soy otaku :v</p>
      <p>
        <a href="#" class="btn btn-dark my-2">Ir a Ultimas Tendencias</a>
        <a href="#" class="btn btn-secondary my-2">Ver m&aacute;s personajes</a>
      </p>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row">
        {% for char in characters%}
        <div class="col-md-4">
          <div class="card mb-4 box-shadow" style="width: 23rem;">
            <img class="card-img-top" style="width: 23rem; height: 35rem; " src="{{char.image}}" alt="{{char.name}}">
            <div class="card-body">
                <h5 class="card-title">{{char.name}}</h5>
                <h6 class="card-subtitle mb-2 text-muted">{{char.anime}}</h6>
              <p class="card-text" style="text-align: justify; height: 10rem;">{{char.desc}}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">Ver</button>
                  <button type="button" class="btn btn-sm btn-dark">Ver más</button>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
  {% endblock content %}

  <footer class="text-muted">
    <div class="container">
      <p class="float-right">
        <a href="{% url 'index' %}">Regresar al tope</a>
      </p>
      <p>Ejemplo de Tienda de Productos &copy; Bootstrap.</p>
      <p>¿Nuevos en Bootstrap? <a href="../../">Visiten la pagina oficial </a> o consulten <a href="../../getting-started/"> la guía de inicio</a>.</p>
    </div>
  </footer>

frontend/app/templates/notify.html
{% extends "base.html" %}
{% block content %}


{% endblock content %}